// <auto-generated />
namespace PiggyFarmy1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addHeoandChuongHeoandrelatetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addHeoandChuongHeoandrelatetable));
        
        string IMigrationMetadata.Id
        {
            get { return "202310210245225_add Heo and ChuongHeo and relate table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
