// <auto-generated />
namespace PiggyFarmy1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class chinhsuachuongvaloaichuong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chinhsuachuongvaloaichuong));
        
        string IMigrationMetadata.Id
        {
            get { return "202311061308103_chinh sua chuong va loai chuong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
